// 11_SSR_Nuxt3_Nextjs/01-Vue3-SSR/05-vue3-ssr-router/src/views/about.vue
<template>
  <div class="app" style="border: 1px solid blue; margin: 10px">
    <h2>About</h2>
    <div>{{ count }}</div>
    <button @click="addCounter">+1</button>
  </div>
</template>

<script setup>
import { ref } from "vue";
const count = ref(300);
function addCounter() {
  count.value++;
}
</script>

// 11_SSR_Nuxt3_Nextjs/03-React18-SSR/04-react18-ssr-router/src/pages/about.jsx
import React, { useState } from "react";
const About = function () {
  const [counter, setCounter] = useState(300);
  function addCounter() {
    setCounter(counter + 1);
  }
  return (
    <div className="About" style={{ border: "2px solid blue", margin: "20px" }}>
      <h3>About</h3>
      <div>{counter}</div>
      <button onClick={addCounter}>+1</button>
    </div>
  );
};

export default About;
