// 10_React_TS_Music_project/11_SSR_Nuxt3_Nextjs/01-Vue3-SSR/03-vue3-ssr-server-hydration/src/App.vue
<template>
  <div class="app" style="border: 1px solid red">
    <h2>Vue3 App</h2>
    <div>{{ count }}</div>
    <button @click="addCounter">+1</button>
  </div>
</template>

<script setup>
import { ref } from "vue";
const count = ref(100);
function addCounter() {
  count.value++;
}
</script>

// 11_SSR_Nuxt3_Nextjs/03-React18-SSR/01-react18-ssr-server/src/app.jsx
import React from "react";
import { useState } from "react";

const App = function () {
  const [counter, setCounter] = useState(100);

  function addCounter() {
    setCounter(counter);
  }
  return (
    <div>
      <h2>App</h2>
      <div>{counter}</div>
      <button onClick={addCounter}>+1</button>
    </div>
  );
};

export default App;
