// 10_React_TS_Music项目实战/11_SSR_Nuxt3_Nextjs/01-Vue3-SSR/06-vue3-ssr-pinia/src/views/home.vue
<template>
  <div class="app" style="border: 1px solid green; margin: 10px">
    <h2>Home</h2>
    <div>{{ count }}</div>
    <button @click="addCounter">+1</button>
  </div>
</template>

<script setup>
import { storeToRefs } from "pinia";
import { useHomeStore } from "../store/home";
let homeStore = useHomeStore();
let { count } = storeToRefs(homeStore);
function addCounter() {
  count.value++;
}
</script>

// 10_React_TS_Music_project/11_SSR_Nuxt3_Nextjs/03-React18-SSR/04-react18-ssr-router/src/pages/home.jsx
import React, { useState } from "react";
const Home = function () {
  const [counter, setCounter] = useState(200);
  function addCounter() {
    setCounter(counter + 1);
  }
  return (
    <div className="Home" style={{ border: "2px solid green", margin: "10px" }}>
      <h3>Home</h3>
      <div>{counter}</div>
      <button onClick={addCounter}>+1</button>
    </div>
  );
};

export default Home;
